// Code generated by protoc-gen-go.
// source: StreamTrade.proto
// DO NOT EDIT!

/*
Package sd_StreamTrade is a generated protocol buffer package.

It is generated from these files:
	StreamTrade.proto

It has these top-level messages:
	Price
	Symbol
	Time
	StreamTrade
*/
package sd_StreamTrade

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Price struct {
	Precision        *uint32  `protobuf:"varint,1,opt,name=precision" json:"precision,omitempty"`
	Price            *float64 `protobuf:"fixed64,2,opt,name=price" json:"price,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Price) Reset()                    { *m = Price{} }
func (m *Price) String() string            { return proto.CompactTextString(m) }
func (*Price) ProtoMessage()               {}
func (*Price) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Price) GetPrecision() uint32 {
	if m != nil && m.Precision != nil {
		return *m.Precision
	}
	return 0
}

func (m *Price) GetPrice() float64 {
	if m != nil && m.Price != nil {
		return *m.Price
	}
	return 0
}

type Symbol struct {
	SymbolStr        *string `protobuf:"bytes,1,opt,name=symbolStr" json:"symbolStr,omitempty"`
	SymbolType       *int32  `protobuf:"varint,2,opt,name=symbolType" json:"symbolType,omitempty"`
	ExchangeType     *int32  `protobuf:"varint,3,opt,name=exchangeType" json:"exchangeType,omitempty"`
	CountryType      *int32  `protobuf:"varint,4,opt,name=countryType" json:"countryType,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Symbol) Reset()                    { *m = Symbol{} }
func (m *Symbol) String() string            { return proto.CompactTextString(m) }
func (*Symbol) ProtoMessage()               {}
func (*Symbol) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Symbol) GetSymbolStr() string {
	if m != nil && m.SymbolStr != nil {
		return *m.SymbolStr
	}
	return ""
}

func (m *Symbol) GetSymbolType() int32 {
	if m != nil && m.SymbolType != nil {
		return *m.SymbolType
	}
	return 0
}

func (m *Symbol) GetExchangeType() int32 {
	if m != nil && m.ExchangeType != nil {
		return *m.ExchangeType
	}
	return 0
}

func (m *Symbol) GetCountryType() int32 {
	if m != nil && m.CountryType != nil {
		return *m.CountryType
	}
	return 0
}

type Time struct {
	Year             *uint32 `protobuf:"varint,1,opt,name=year" json:"year,omitempty"`
	Month            *uint32 `protobuf:"varint,2,opt,name=month" json:"month,omitempty"`
	DayOfWeek        *uint32 `protobuf:"varint,3,opt,name=dayOfWeek" json:"dayOfWeek,omitempty"`
	Day              *uint32 `protobuf:"varint,4,opt,name=day" json:"day,omitempty"`
	Hour             *uint32 `protobuf:"varint,5,opt,name=hour" json:"hour,omitempty"`
	Minute           *uint32 `protobuf:"varint,6,opt,name=minute" json:"minute,omitempty"`
	Second           *uint32 `protobuf:"varint,7,opt,name=second" json:"second,omitempty"`
	Milliseconds     *uint32 `protobuf:"varint,8,opt,name=milliseconds" json:"milliseconds,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Time) Reset()                    { *m = Time{} }
func (m *Time) String() string            { return proto.CompactTextString(m) }
func (*Time) ProtoMessage()               {}
func (*Time) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Time) GetYear() uint32 {
	if m != nil && m.Year != nil {
		return *m.Year
	}
	return 0
}

func (m *Time) GetMonth() uint32 {
	if m != nil && m.Month != nil {
		return *m.Month
	}
	return 0
}

func (m *Time) GetDayOfWeek() uint32 {
	if m != nil && m.DayOfWeek != nil {
		return *m.DayOfWeek
	}
	return 0
}

func (m *Time) GetDay() uint32 {
	if m != nil && m.Day != nil {
		return *m.Day
	}
	return 0
}

func (m *Time) GetHour() uint32 {
	if m != nil && m.Hour != nil {
		return *m.Hour
	}
	return 0
}

func (m *Time) GetMinute() uint32 {
	if m != nil && m.Minute != nil {
		return *m.Minute
	}
	return 0
}

func (m *Time) GetSecond() uint32 {
	if m != nil && m.Second != nil {
		return *m.Second
	}
	return 0
}

func (m *Time) GetMilliseconds() uint32 {
	if m != nil && m.Milliseconds != nil {
		return *m.Milliseconds
	}
	return 0
}

type StreamTrade struct {
	MessageId        *string           `protobuf:"bytes,1,opt,name=messageId" json:"messageId,omitempty"`
	Data             *StreamTrade_Data `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *StreamTrade) Reset()                    { *m = StreamTrade{} }
func (m *StreamTrade) String() string            { return proto.CompactTextString(m) }
func (*StreamTrade) ProtoMessage()               {}
func (*StreamTrade) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *StreamTrade) GetMessageId() string {
	if m != nil && m.MessageId != nil {
		return *m.MessageId
	}
	return ""
}

func (m *StreamTrade) GetData() *StreamTrade_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type StreamTrade_Data struct {
	Symbol           *Symbol `protobuf:"bytes,1,opt,name=Symbol" json:"Symbol,omitempty"`
	Condition        *uint32 `protobuf:"varint,2,opt,name=condition" json:"condition,omitempty"`
	LastExchange     *uint32 `protobuf:"varint,3,opt,name=lastExchange" json:"lastExchange,omitempty"`
	LastPrice        *Price  `protobuf:"bytes,4,opt,name=lastPrice" json:"lastPrice,omitempty"`
	LastSize         *uint32 `protobuf:"varint,5,opt,name=lastSize" json:"lastSize,omitempty"`
	Time             *Time   `protobuf:"bytes,6,opt,name=time" json:"time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StreamTrade_Data) Reset()                    { *m = StreamTrade_Data{} }
func (m *StreamTrade_Data) String() string            { return proto.CompactTextString(m) }
func (*StreamTrade_Data) ProtoMessage()               {}
func (*StreamTrade_Data) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

func (m *StreamTrade_Data) GetSymbol() *Symbol {
	if m != nil {
		return m.Symbol
	}
	return nil
}

func (m *StreamTrade_Data) GetCondition() uint32 {
	if m != nil && m.Condition != nil {
		return *m.Condition
	}
	return 0
}

func (m *StreamTrade_Data) GetLastExchange() uint32 {
	if m != nil && m.LastExchange != nil {
		return *m.LastExchange
	}
	return 0
}

func (m *StreamTrade_Data) GetLastPrice() *Price {
	if m != nil {
		return m.LastPrice
	}
	return nil
}

func (m *StreamTrade_Data) GetLastSize() uint32 {
	if m != nil && m.LastSize != nil {
		return *m.LastSize
	}
	return 0
}

func (m *StreamTrade_Data) GetTime() *Time {
	if m != nil {
		return m.Time
	}
	return nil
}

func init() {
	proto.RegisterType((*Price)(nil), "sd.StreamTrade.Price")
	proto.RegisterType((*Symbol)(nil), "sd.StreamTrade.Symbol")
	proto.RegisterType((*Time)(nil), "sd.StreamTrade.Time")
	proto.RegisterType((*StreamTrade)(nil), "sd.StreamTrade.StreamTrade")
	proto.RegisterType((*StreamTrade_Data)(nil), "sd.StreamTrade.StreamTrade.Data")
}

func init() { proto.RegisterFile("StreamTrade.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x91, 0xc1, 0x4e, 0xf3, 0x30,
	0x0c, 0xc7, 0xd5, 0xad, 0xdd, 0xb7, 0xb9, 0xeb, 0xf4, 0x2d, 0x0c, 0x54, 0x71, 0x9a, 0x7a, 0x40,
	0xe3, 0xd2, 0x43, 0x9f, 0x01, 0x0e, 0x9c, 0x40, 0xea, 0x24, 0x24, 0x6e, 0xa1, 0x35, 0x5b, 0x44,
	0xd3, 0x54, 0x49, 0x26, 0x51, 0x5e, 0x00, 0x89, 0x17, 0xe2, 0xf5, 0x50, 0xdc, 0x0e, 0xb6, 0x71,
	0xb3, 0x7f, 0xb1, 0xff, 0xb1, 0xff, 0x86, 0x79, 0x6e, 0x35, 0x72, 0xb9, 0xd6, 0xbc, 0xc4, 0xb4,
	0xd1, 0xca, 0x2a, 0x36, 0x33, 0x65, 0x7a, 0x40, 0x93, 0x6b, 0x08, 0x1e, 0xb4, 0x28, 0x90, 0xcd,
	0x61, 0xd2, 0x68, 0x2c, 0x84, 0x11, 0xaa, 0x8e, 0xbd, 0xa5, 0xb7, 0x8a, 0x58, 0x04, 0x41, 0xe3,
	0xde, 0xe2, 0xc1, 0xd2, 0x5b, 0x79, 0xc9, 0x13, 0x8c, 0xf2, 0x56, 0x3e, 0xab, 0xca, 0xd5, 0x1a,
	0x8a, 0x72, 0xab, 0xa9, 0x76, 0xc2, 0x18, 0x40, 0x87, 0xd6, 0x6d, 0xd3, 0x35, 0x04, 0x6c, 0x01,
	0x53, 0x7c, 0x2b, 0xb6, 0xbc, 0xde, 0x20, 0xd1, 0x21, 0xd1, 0x33, 0x08, 0x0b, 0xb5, 0xab, 0xad,
	0x6e, 0x09, 0xfa, 0x0e, 0x26, 0x1f, 0x1e, 0xf8, 0x6b, 0x21, 0x91, 0x4d, 0xc1, 0x6f, 0x91, 0xeb,
	0xdf, 0x09, 0xa4, 0xaa, 0xed, 0x96, 0x04, 0x23, 0xf7, 0x6f, 0xc9, 0xdb, 0xfb, 0x97, 0x47, 0xc4,
	0x57, 0x52, 0x8b, 0x58, 0x08, 0xc3, 0x92, 0xb7, 0xa4, 0x12, 0xb9, 0xe6, 0xad, 0xda, 0xe9, 0x38,
	0xa0, 0x6c, 0x06, 0x23, 0x29, 0xea, 0x9d, 0xc5, 0x78, 0xb4, 0xcf, 0x0d, 0x16, 0xaa, 0x2e, 0xe3,
	0x7f, 0x94, 0x2f, 0x60, 0x2a, 0x45, 0x55, 0x89, 0x0e, 0x9a, 0x78, 0xec, 0x68, 0xf2, 0x39, 0x80,
	0xf0, 0xc0, 0x20, 0xf7, 0xa7, 0x44, 0x63, 0xf8, 0x06, 0xef, 0xca, 0x7e, 0xd7, 0x14, 0xfc, 0x92,
	0x5b, 0x4e, 0x43, 0x85, 0xd9, 0x32, 0x3d, 0xb6, 0xf4, 0x28, 0xbe, 0xe1, 0x96, 0x5f, 0x7e, 0x79,
	0xe0, 0xbb, 0x80, 0x5d, 0xed, 0x1d, 0x24, 0xa1, 0x30, 0xbb, 0xf8, 0xd3, 0xfa, 0xe3, 0xaf, 0x1b,
	0x49, 0x58, 0x77, 0x8b, 0xc1, 0x7e, 0xd8, 0x8a, 0x1b, 0x7b, 0xdb, 0xfb, 0xd9, 0x6f, 0xbf, 0x82,
	0x89, 0xa3, 0x74, 0x41, 0xf2, 0x20, 0xcc, 0xce, 0x4f, 0x35, 0xbb, 0xf3, 0xfe, 0x87, 0xb1, 0xab,
	0xcc, 0xc5, 0x3b, 0xf6, 0xf6, 0x24, 0xe0, 0x5b, 0x21, 0x3b, 0x73, 0xc2, 0x6c, 0x71, 0xda, 0xe6,
	0xae, 0xf1, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x96, 0x87, 0x4d, 0x6c, 0x41, 0x02, 0x00, 0x00,
}
